/// Tabela-ponte curso -> programa (muitos-para-muitos: um curso pode estar em
/// varios programas, inclusive do mesmo publico). Carregada de
/// docs/dashboard_programa.csv. Liga-se a dim_curso por id_curso com filtro
/// bidirecional, para que selecionar um programa filtre o fato.
table bridge_programa
	lineageTag: f7d7a7ec-617d-48fd-afbc-392383c71a17

	column id_curso
		dataType: int64
		formatString: 0
		lineageTag: 1e9f62cd-e1f8-4a9a-9b69-5d7af18958fd
		summarizeBy: none
		sourceColumn: id_curso

	column nome_curso
		dataType: string
		lineageTag: 21305109-5a97-496e-9fb6-938be07dbec7
		summarizeBy: none
		sourceColumn: nome_curso

	column programa
		dataType: string
		lineageTag: 3898bfd9-06fe-4abb-88a6-4206c9453a2d
		summarizeBy: none
		sourceColumn: programa

	column publico_alvo
		dataType: string
		lineageTag: 2aee569d-8064-48ba-a0ac-15eaa04ff003
		summarizeBy: none
		sourceColumn: publico_alvo

	partition bridge_programa = m
		mode: import
		source =
				let
					Folder = Text.BeforeDelimiter(CsvPath, "/", {0, RelativePosition.FromEnd}),
					ProgPath = Folder & "/dashboard_programa.csv",
					Source = Csv.Document(File.Contents(ProgPath), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {
						{"id_curso", Int64.Type},
						{"nome_curso", type text},
						{"programa", type text},
						{"publico_alvo", type text}
					})
				in
					Typed

	annotation PBI_ResultType = Table

