/// Tabela fato unica gerada por scripts/gerar_base_dashboard.py
/// 385k linhas — schema flat (sem dimensoes separadas).
table dashboard_base
	lineageTag: 45024c93-3e9a-449d-a9b4-1bc451368289

	measure 'Matriculas' = COUNTROWS(dashboard_base)
		formatString: #,0
		lineageTag: aaec4cc1-1333-4265-859a-8a9291b074c2

	measure 'Matriculas IA' = CALCULATE([Matriculas], dashboard_base[ia] = 1)
		formatString: #,0
		lineageTag: a27fb1fa-c40b-42fd-ba01-674dab67b6c4

	measure 'Pessoas Unicas' = DISTINCTCOUNT(dashboard_base[codigo_pessoa])
		formatString: #,0
		lineageTag: 06742375-6ac6-4ddc-996c-c70a35e5b643

	measure 'Pessoas Unicas IA' = CALCULATE([Pessoas Unicas], dashboard_base[ia] = 1)
		formatString: #,0
		lineageTag: 49d19b49-cf2d-4bae-a0fb-6ffc82b76c70

	measure '% Matriculas IA' = DIVIDE([Matriculas IA], [Matriculas])
		formatString: 0.0%
		lineageTag: efbd6d9d-d1cc-4a65-8729-51ffe9f34d0b

	column ano_mes
		dataType: string
		sourceColumn: ano_mes
		sortByColumn: ano_mes_sort
		summarizeBy: none
		lineageTag: c9223556-3433-4571-85b9-77d8b8fa94c2

	column ano
		dataType: int64
		sourceColumn: ano
		formatString: 0
		summarizeBy: none
		lineageTag: 7ec13e53-b02b-428d-8513-aff3edd5a308

	column mes
		dataType: int64
		sourceColumn: mes
		formatString: 0
		summarizeBy: none
		lineageTag: b02f752d-fdce-4d29-87d0-326c2c48e406

	column id_curso
		dataType: int64
		sourceColumn: id_curso
		formatString: 0
		summarizeBy: none
		lineageTag: 19a11d26-3fc1-4166-94e5-2d108670520f

	column nome_curso
		dataType: string
		sourceColumn: nome_curso
		summarizeBy: none
		lineageTag: ab3d2b75-1b3c-4ec6-a0ca-e8c87ddfd397

	column ia
		dataType: int64
		sourceColumn: ia
		formatString: 0
		summarizeBy: none
		lineageTag: 7f66c5ef-5325-4313-91fb-f98b3320de4d

	column esfera
		dataType: string
		sourceColumn: esfera
		summarizeBy: none
		lineageTag: 710b7ae4-fc26-4619-af5c-ce5734fc3d30

	column setor
		dataType: string
		sourceColumn: setor
		summarizeBy: none
		lineageTag: 85366ba0-f1cc-4d76-ac5a-91ed19552ad5

	column poder
		dataType: string
		sourceColumn: poder
		summarizeBy: none
		lineageTag: 85058cd5-b75a-4abd-922c-bbecdea60d2c

	column codigo_pessoa
		dataType: string
		sourceColumn: codigo_pessoa
		isHidden
		summarizeBy: none
		lineageTag: f215d4b6-62c8-4091-a389-039253c30c18

	/// Coluna calculada para ordenacao cronologica do eixo de linha temporal.
	column ano_mes_sort = ([ano] * 100) + [mes]
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		lineageTag: 3936d047-2a9b-4527-be0d-386c9249efcd

	/// Rotulo legivel de IA para uso em slicers e visuais.
	column ia_label = IF(dashboard_base[ia] = 1, "IA", "Nao IA")
		dataType: string
		summarizeBy: none
		lineageTag: 6b43369b-2e69-41ad-8f4b-71802771ef36

	partition dashboard_base = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(CsvPath), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {
						{"ano_mes", type text},
						{"ano", Int64.Type},
						{"mes", Int64.Type},
						{"id_curso", Int64.Type},
						{"nome_curso", type text},
						{"ia", Int64.Type},
						{"esfera", type text},
						{"setor", type text},
						{"poder", type text},
						{"codigo_pessoa", type text}
					})
				in
					Typed

	annotation PBI_ResultType = Table
